server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka

spring:
  main:
    allow-bean-definition-overriding: true
  application:
   name: account-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true