server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka

spring:
  data:
  application:
   name: ticket-service
  datasource:
    url: jdbc:mysql://localhost:3306/SpringCloudApp
    username: root
    password: mysql
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update